#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JRide.Resource", IsApplication=true)]

namespace JRide
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btnCarroSeleccionado = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int btnEntrar = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int etContrasena = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int etUsuario = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int lvListaCarro = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int tvDescripcionCarro = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tvPlacas = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ItemCarro = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SeleccionarCarro = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int ApplicationName = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int BtnSeleccionarCarro = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Contrasena = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Entrar = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Hello = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int SeleccionarCarro = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Usuario = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
